version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore samplecoreappforaws/samplecoreappforaws.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output samplecoreappforaws/samplecoreappforaws.csproj
      - dotnet test -c release ./samplecoretestforaws/samplecoretestforaws.csproj --logger trx --results-directory ./testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
artifacts:
  files:
    - '**/*'
  base-directory: '../src/build_output'  
